### ISSUE TITLE
install ko

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/chatonsinfos_ynh#4]
install is ko 
there is the complete log: 
https://paste.yunohost.org/raw/gikimawaro

thx for your eyes ;)

**Comment by alexAubin** [comment]
Yes indeed, the manifest sources should point to a specific commit or version and not just master ... https://github.com/YunoHost-Apps/chatonsinfos_ynh/blob/testing/manifest.toml#L46
